---
apiVersion: v1 #write on a different file
kind: PersistentVolumeClaim
metadata:
  name: mongo
  labels:
    app: mongo    
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017 
          name: mongo
        volumeMounts:
        - name: mongo
          mountPath: /data/db
      volumes:
      - name: mongo
        persistentVolumeClaim:
          claimName: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017 # port number exposed internally in cluster - change what I want
      targetPort: 27017 #port that containers are listening to 
  selector:
    app: mongo