---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharelatex-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharelatex-deployment
spec:
  selector:
    matchLabels:
      app: overleaf-on-docker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: overleaf-on-docker
    spec:
      containers:
      - name: overleaf
        env:
          - name: ENABLED_LINKED_FILE_TYPES
            value: url,project_file
          - name: ENABLE_CONVERSIONS
            value: "true"
          - name: REDIS_HOST
            value: redis
          - name: SHARELATEX_APP_NAME
            value: Overleaf Community Edition
          - name: SHARELATEX_MONGO_URL
            value: mongodb://mongo/sharelatex
          - name: SHARELATEX_REDIS_HOST
            value: redis
        image: sharelatex/sharelatex
        volumeMounts:
          - name: sharelatex-claim
            mountPath: /network-ceph/lpomer/sharelatex
          - mountPath: "/network-ceph/lpomer"
            name: fsmount
          #var/lib/sharelatex
          # mountPath: /var/run/docker.sock
        ports:
          - name: sharelatex-port
            containerPort: 80
      volumes:
        - name: fsmount
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              fsName: home
              clusterNamespace: rook-ceph
        - name: sharelatex-claim
          persistentVolumeClaim:
            claimName: sharelatex-claim
      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sharelatex
  name: sharelatex
spec:
  type: NodePort
  ports:
  - name: "100" #?
    port: 80 #port number exposed internally in cluster
    targetPort: 80 #port that containers are listening to 
  selector:
    app: overleaf-on-docker  